name = "ai-example"
main = "src/index.js"
compatibility_date = "2024-01-10"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "database"
database_id = "2e42cada-aff5-411e-aa8f-66bf96932842"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "vector-index"